services:
  peloton:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: peloton
    ports:
      - 8555:8000
    environment:
      MONGODB_HOSTNAME: mongodb
    volumes:
      - .:/workspaces/peloton
    restart: unless-stopped
  
  mongodb:
    image: mongo:4.4.18
    container_name: mongodb
    environment:
      PUID: 1000
      PGUID: 1000
      TZ: 'America/New_York'
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
    
volumes:
  mongodb-data: