version: '3.8'
services:
  peloton:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: peloton
    ports:
      - 8555:8000
    env_file:
      - /home/zvaughan/python/.env
    volumes:
      - .:/workspaces/peloton
    restart: unless-stopped